export type Category =
  | "AI" | "Business" | "Money" | "Filmmaking" | "Music"
  | "Design" | "Productivity" | "Psychology" | "Startups" | "Creator Growth";

export const CATEGORIES: Category[] = [
  "AI","Business","Money","Filmmaking","Music",
  "Design","Productivity","Psychology","Startups","Creator Growth",
];

export interface FeedPost {
  id: string;
  title: string;
  platform: string;
  url: string;
  category: Category;
  summary: string;
  whyUseful: string;
  actionStep: string;
  timeToConsume: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  tags: string[];
}

export const MOCK_POSTS: FeedPost[] = [
  {
    id: "1",
    title: "How to actually use Claude as a thinking partner",
    platform: "YouTube",
    url: "https://www.youtube.com",
    category: "AI",
    summary: "Prompt patterns that turn LLMs into research collaborators instead of toy chatbots.",
    whyUseful: "Most people use AI as a search engine. This reframes it as a structured reasoning tool you can compound on.",
    actionStep: "Run one decision you're stuck on through the 'steelman both sides' prompt in Claude.",
    timeToConsume: "9 min",
    difficulty: "Beginner",
    tags: ["llm", "workflow", "prompting"],
  },
  {
    id: "2",
    title: "Building production RAG systems that don't hallucinate",
    platform: "Article",
    url: "https://www.pinecone.io/learn/",
    category: "AI",
    summary: "Chunking, hybrid search, and re-ranking patterns from teams shipping RAG at scale.",
    whyUseful: "Skips the toy demos and shows the boring infrastructure decisions that determine whether RAG actually works.",
    actionStep: "Add a re-ranker to your existing RAG pipeline and measure precision before/after.",
    timeToConsume: "18 min",
    difficulty: "Advanced",
    tags: ["rag", "vector-db", "llm"],
  },
  {
    id: "3",
    title: "Andrej Karpathy: Intro to Large Language Models",
    platform: "YouTube",
    url: "https://www.youtube.com/watch?v=zjkBMFhNj_g",
    category: "AI",
    summary: "A one-hour mental model for how LLMs are trained, fine-tuned, and deployed.",
    whyUseful: "The clearest first-principles explanation of LLMs from one of the field's best teachers.",
    actionStep: "Watch it once at 1x, then sketch the training pipeline from memory.",
    timeToConsume: "60 min",
    difficulty: "Intermediate",
    tags: ["llm", "fundamentals", "karpathy"],
  },
  {
    id: "4",
    title: "The one-page business model that beats a 30-page plan",
    platform: "Article",
    url: "https://www.strategyzer.com/library",
    category: "Business",
    summary: "A condensed walkthrough of the lean canvas with examples from real bootstrapped companies.",
    whyUseful: "Forces clarity on customer, problem, and unfair advantage in under an hour.",
    actionStep: "Fill out a lean canvas for your current idea before you write any more code.",
    timeToConsume: "12 min",
    difficulty: "Beginner",
    tags: ["strategy", "mvp"],
  },
  {
    id: "5",
    title: "Jobs-to-be-Done: stop selling features, start selling progress",
    platform: "Essay",
    url: "https://jtbd.info/",
    category: "Business",
    summary: "Christensen's framework for understanding why customers actually 'hire' a product.",
    whyUseful: "Reveals the real competition for your product is rarely what you think — and rewrites your positioning overnight.",
    actionStep: "Interview 3 recent customers about the day they decided to buy. Look for the trigger.",
    timeToConsume: "15 min",
    difficulty: "Intermediate",
    tags: ["jtbd", "positioning"],
  },
  {
    id: "6",
    title: "Index funds explained without the bro energy",
    platform: "Wiki",
    url: "https://www.bogleheads.org/wiki/Three-fund_portfolio",
    category: "Money",
    summary: "A calm primer on three-fund portfolios, expense ratios, and why timing the market loses.",
    whyUseful: "Replaces hours of finance content with the actual math that compounds over decades.",
    actionStep: "Check the expense ratio of every fund you own. Anything above 0.2% — investigate.",
    timeToConsume: "22 min",
    difficulty: "Beginner",
    tags: ["investing", "personal-finance"],
  },
  {
    id: "7",
    title: "The Psychology of Money — key ideas in 10 minutes",
    platform: "Long-read",
    url: "https://collabfund.com/blog/the-psychology-of-money/",
    category: "Money",
    summary: "Morgan Housel on how behavior, not intelligence, decides who builds wealth.",
    whyUseful: "Reframes money as a behavioral game — most spreadsheets miss the variable that actually matters.",
    actionStep: "Automate one transfer to savings tomorrow so the decision stops being a decision.",
    timeToConsume: "10 min",
    difficulty: "Beginner",
    tags: ["wealth", "behavior"],
  },
  {
    id: "8",
    title: "Paul Graham — Do Things That Don't Scale",
    platform: "Essay",
    url: "https://www.paulgraham.com/ds.html",
    category: "Startups",
    summary: "The classic essay on why early-stage founders should manually recruit users one by one.",
    whyUseful: "Cures the 'if we build it they will come' delusion that kills most early startups.",
    actionStep: "DM 10 ideal users today and personally onboard whoever responds.",
    timeToConsume: "8 min",
    difficulty: "Beginner",
    tags: ["yc", "early-stage"],
  },
  {
    id: "9",
    title: "Y Combinator's request for startups, decoded",
    platform: "Essay",
    url: "https://www.ycombinator.com/rfs",
    category: "Startups",
    summary: "What YC partners actually mean by each category and where the gaps are.",
    whyUseful: "Free signal on where serious capital thinks the next decade is going.",
    actionStep: "Pick one RFS category and write a one-page thesis for a company in it.",
    timeToConsume: "13 min",
    difficulty: "Intermediate",
    tags: ["yc", "ideas"],
  },
  {
    id: "10",
    title: "How First Round finds product-market fit",
    platform: "Article",
    url: "https://review.firstround.com/",
    category: "Startups",
    summary: "Tactical PMF playbook from First Round Review's interviews with breakout founders.",
    whyUseful: "Replaces vague 'PMF' talk with measurable signals you can actually track weekly.",
    actionStep: "Run the Sean Ellis 'how would you feel if you couldn't use this' survey on 40 users.",
    timeToConsume: "20 min",
    difficulty: "Intermediate",
    tags: ["pmf", "growth"],
  },
  {
    id: "11",
    title: "Building an audience without becoming a content slave",
    platform: "Essay",
    url: "https://every.to/",
    category: "Creator Growth",
    summary: "A sustainable cadence model based on one heavy asset plus daily atomic posts.",
    whyUseful: "Avoids the burnout loop most creators hit at month 4.",
    actionStep: "Plan one long-form piece this week and 5 atomic posts derived from it.",
    timeToConsume: "6 min",
    difficulty: "Beginner",
    tags: ["audience", "writing"],
  },
  {
    id: "12",
    title: "1000 True Fans by Kevin Kelly",
    platform: "Essay",
    url: "https://kk.org/thetechnium/1000-true-fans/",
    category: "Creator Growth",
    summary: "The foundational essay on building a sustainable creator business with a small, loyal audience.",
    whyUseful: "Kills the vanity-metrics chase and shows the math behind a real creator income.",
    actionStep: "Calculate your number: how much would 1000 fans need to pay you per year to live?",
    timeToConsume: "9 min",
    difficulty: "Beginner",
    tags: ["audience", "business"],
  },
  {
    id: "13",
    title: "How to write a Twitter thread people actually finish",
    platform: "Twitter thread",
    url: "https://twitter.com",
    category: "Creator Growth",
    summary: "Hook, payoff, pacing — a teardown of viral threads with the structural patterns highlighted.",
    whyUseful: "Most threads die on the first tweet. This shows you the exact reason and how to fix it.",
    actionStep: "Rewrite your last thread's hook 5 different ways and post the strongest one.",
    timeToConsume: "7 min",
    difficulty: "Beginner",
    tags: ["twitter", "writing"],
  },
  {
    id: "14",
    title: "Shooting cinematic b-roll with one lens",
    platform: "YouTube",
    url: "https://www.youtube.com",
    category: "Filmmaking",
    summary: "A working DP shows how composition and movement matter more than gear.",
    whyUseful: "Cuts through gear-acquisition syndrome with constraints that force better shots.",
    actionStep: "Shoot 10 b-roll clips this week using only a 35mm equivalent.",
    timeToConsume: "14 min",
    difficulty: "Intermediate",
    tags: ["cinematography", "composition"],
  },
  {
    id: "15",
    title: "Color grading: from flat log footage to a film look",
    platform: "YouTube",
    url: "https://www.youtube.com",
    category: "Filmmaking",
    summary: "A node-based DaVinci Resolve walkthrough that demystifies primary and secondary grading.",
    whyUseful: "Color is what separates 'home video' from 'cinematic' — this is the shortest path there.",
    actionStep: "Grade one shot tonight using only lift/gamma/gain before touching any LUT.",
    timeToConsume: "17 min",
    difficulty: "Intermediate",
    tags: ["color", "resolve", "post"],
  },
  {
    id: "16",
    title: "Why good UI is mostly spacing",
    platform: "Article",
    url: "https://www.refactoringui.com/",
    category: "Design",
    summary: "Practical rules from Refactoring UI on hierarchy, weight, and density.",
    whyUseful: "Gives non-designers a checklist that immediately raises the floor of their work.",
    actionStep: "Audit one screen of your product and double the whitespace around primary CTAs.",
    timeToConsume: "8 min",
    difficulty: "Beginner",
    tags: ["ui", "whitespace"],
  },
  {
    id: "17",
    title: "Designing accessible color systems",
    platform: "Article",
    url: "https://stripe.com/blog/accessible-color-systems",
    category: "Design",
    summary: "How Stripe rebuilt their color palette to hit WCAG AA across every surface.",
    whyUseful: "A real-world case study with the math behind perceptually uniform color scales.",
    actionStep: "Run your primary brand color through an APCA contrast checker on light and dark backgrounds.",
    timeToConsume: "12 min",
    difficulty: "Intermediate",
    tags: ["color", "a11y", "design-systems"],
  },
  {
    id: "18",
    title: "The Dieter Rams 10 principles of good design",
    platform: "Reference",
    url: "https://www.vitsoe.com/us/about/good-design",
    category: "Design",
    summary: "The principles that shaped Braun, Apple, and most products you actually love.",
    whyUseful: "A timeless filter to evaluate any design decision you're about to ship.",
    actionStep: "Pick one screen of your product and rate it 1-10 against each of the 10 principles.",
    timeToConsume: "5 min",
    difficulty: "Beginner",
    tags: ["principles", "industrial-design"],
  },
  {
    id: "19",
    title: "Time-blocking that actually survives Tuesday",
    platform: "Newsletter",
    url: "https://blog.doist.com/time-blocking/",
    category: "Productivity",
    summary: "A realistic system that accounts for interruptions and energy levels.",
    whyUseful: "Most productivity systems collapse on contact with reality. This one doesn't.",
    actionStep: "Block 90 minutes tomorrow morning for your single most important task.",
    timeToConsume: "7 min",
    difficulty: "Beginner",
    tags: ["focus", "planning"],
  },
  {
    id: "20",
    title: "Cal Newport on Deep Work in a distracted world",
    platform: "Podcast",
    url: "https://www.calnewport.com/podcast/",
    category: "Productivity",
    summary: "Concrete protocols for reclaiming 4 hours of focused output a day.",
    whyUseful: "Replaces vague 'focus' advice with rituals you can actually run starting tomorrow.",
    actionStep: "Put your phone in another room for one 90-minute deep work block today.",
    timeToConsume: "45 min",
    difficulty: "Beginner",
    tags: ["deep-work", "focus"],
  },
];
