import {
  Cpu,
  Wallet,
  PenTool,
  Newspaper,
  BookOpen,
  HeartPulse,
  Utensils,
  Briefcase,
  type LucideIcon,
} from "lucide-react";

export type Category =
  | "AI & Tech"
  | "Money"
  | "Creativity"
  | "News & Current Affairs"
  | "Mind & Philosophy"
  | "Health & Lifestyle"
  | "Cooking & Skills"
  | "Business";

export type ContentType = "Video" | "Article" | "Tool" | "Idea" | "News" | "Tip";
export type Difficulty = "Easy" | "Medium" | "Deep";

export interface CategoryMeta {
  Icon: LucideIcon;
  tone: string;
  blurb: string;
  examples: string[];
}

export const CATEGORY_META: Record<Category, CategoryMeta> = {
  "AI & Tech": {
    Icon: Cpu,
    tone: "text-cyan-300",
    blurb: "Use the tools shaping the future",
    examples: ["AI tools", "gadgets", "cybersecurity", "software"],
  },
  "Money": {
    Icon: Wallet,
    tone: "text-emerald-300",
    blurb: "Save, invest, earn smarter",
    examples: ["saving", "budgeting", "investing", "side hustles"],
  },
  "Creativity": {
    Icon: PenTool,
    tone: "text-purple-300",
    blurb: "Make better, more often",
    examples: ["design", "photoshop", "video", "music"],
  },
  "News & Current Affairs": {
    Icon: Newspaper,
    tone: "text-slate-300",
    blurb: "Understand what's happening",
    examples: ["world events", "explainers", "trends"],
  },
  "Mind & Philosophy": {
    Icon: BookOpen,
    tone: "text-indigo-300",
    blurb: "Think deeper, live calmer",
    examples: ["Stoicism", "Buddhism", "Socrates", "Epicurus"],
  },
  "Health & Lifestyle": {
    Icon: HeartPulse,
    tone: "text-green-300",
    blurb: "Feel better, daily",
    examples: ["wellness", "habits", "self-care"],
  },
  "Cooking & Skills": {
    Icon: Utensils,
    tone: "text-orange-300",
    blurb: "Practical things worth knowing",
    examples: ["recipes", "home skills", "practical tips"],
  },
  "Business": {
    Icon: Briefcase,
    tone: "text-amber-300",
    blurb: "Operator-level thinking",
    examples: ["marketing", "sales", "startup ideas", "customer problems"],
  },
};

export const CATEGORIES: ({ name: Category } & CategoryMeta)[] = (
  Object.keys(CATEGORY_META) as Category[]
).map((name) => ({ name, ...CATEGORY_META[name] }));

export interface Signal {
  id: string;
  title: string;
  category: Category;
  contentType: ContentType;
  sourceName?: string;
  sourceUrl?: string;
  videoUrl?: string;
  shortSummary: string;
  learnInsideApp: string;
  whyItMatters: string;
  quickCheckQuestion: string;
  quickCheckOptions: string[];
  correctAnswer: number; // index into options
  explanationAfterAnswer: string;
  optionalAction?: string;
  estimatedTime: string;
  difficulty: Difficulty;
  tags: string[];
}

const s = (
  id: string,
  category: Category,
  contentType: ContentType,
  title: string,
  shortSummary: string,
  learnInsideApp: string,
  whyItMatters: string,
  quickCheckQuestion: string,
  quickCheckOptions: string[],
  correctAnswer: number,
  explanationAfterAnswer: string,
  optionalAction: string | undefined,
  estimatedTime: string,
  difficulty: Difficulty,
  tags: string[],
  source?: { name: string; url: string },
): Signal => ({
  id,
  title,
  category,
  contentType,
  sourceName: source?.name,
  sourceUrl: source?.url,
  shortSummary,
  learnInsideApp,
  whyItMatters,
  quickCheckQuestion,
  quickCheckOptions,
  correctAnswer,
  explanationAfterAnswer,
  optionalAction,
  estimatedTime,
  difficulty,
  tags,
});

export const DEFAULT_SIGNALS: Signal[] = [
  // ===== AI & Tech =====
  s("ai-1", "AI & Tech", "Tip",
    "Stop rewriting the same AI prompts",
    "Most people waste time writing the same prompts again and again.",
    "A prompt library is a saved collection of prompts you reuse for repeated tasks like writing emails, planning content, summarizing articles, or brainstorming ideas. You build it by saving any prompt that worked once into a notes file or tool, then pasting it next time you need that result.",
    "It turns AI from a random chatbot into a repeatable workflow that compounds in speed every week.",
    "What is the main benefit of a prompt library?",
    ["It makes prompts longer", "It saves reusable prompts for repeated tasks", "It deletes old chats"],
    1,
    "A prompt library helps you reuse good prompts instead of starting from zero every time.",
    "Save 3 prompts you use often into a notes file called 'Prompts'.",
    "5 min", "Easy", ["ai", "workflow"]),
  s("ai-2", "AI & Tech", "Idea",
    "Use AI as a thinking partner, not a search box",
    "The biggest leverage from LLMs comes from structured reasoning, not lookup.",
    "Instead of asking 'what should I do?', ask the model to steelman both sides of a decision, list assumptions, and stress-test the weakest one. This forces it to argue with itself, which usually surfaces what you missed.",
    "Most people use AI like Google. The real edge is using it to argue with you so you make sharper decisions.",
    "Which prompt style usually leads to better thinking?",
    ["Asking for the 'best' answer", "Asking it to steelman both sides", "Asking for shortest response"],
    1,
    "Steelmanning forces the model to surface trade-offs instead of giving a flat opinion.",
    "Take a decision you're stuck on and ask an LLM to steelman both sides.",
    "10 min", "Easy", ["llm", "decisions"]),
  s("ai-3", "AI & Tech", "Video",
    "How LLMs actually work, in 1 hour",
    "Karpathy's intro is the clearest mental model of LLMs that exists.",
    "An LLM is a next-token predictor trained on huge amounts of text. It doesn't 'know' facts — it predicts the most likely next chunk of text given what came before. Fine-tuning and RLHF then shape it to follow instructions.",
    "Once you see LLMs as token predictors, hallucinations and prompt design suddenly make sense.",
    "What does an LLM fundamentally do?",
    ["Look facts up in a database", "Predict the next token from prior text", "Run code on your computer"],
    1,
    "LLMs predict the next token. Everything else (facts, tools, memory) is layered on top.",
    "Watch the first 30 minutes of Karpathy's intro today.",
    "60 min", "Medium", ["llm", "fundamentals"],
    { name: "Intro to LLMs (Karpathy)", url: "https://www.youtube.com/watch?v=zjkBMFhNj_g" }),
  s("ai-4", "AI & Tech", "Tip",
    "Turn on a password manager today",
    "Reusing passwords is how most accounts actually get hacked.",
    "A password manager generates and stores a unique password for every site, locked behind one strong master password and ideally 2FA. Even if one site leaks, the rest of your accounts stay safe because no two passwords match.",
    "It's the single highest-impact 10-minute security upgrade most people never do.",
    "Why does a password manager improve security?",
    ["It hides your IP address", "It gives every account a unique strong password", "It blocks ads"],
    1,
    "Unique passwords mean a leak on one site can't unlock the rest of your life.",
    "Install Bitwarden or 1Password and move 5 accounts in.",
    "15 min", "Easy", ["security", "tools"],
    { name: "Bitwarden", url: "https://bitwarden.com" }),

  // ===== Money =====
  s("mo-1", "Money", "Tip",
    "Audit every subscription you're paying for",
    "The fastest 'raise' most people get is killing dead subscriptions.",
    "Open your bank or card app and search for recurring charges over the last 60 days. List every subscription, mark which you used in the last month, and cancel one you forgot existed. Most people find €10–€40/month of pure waste.",
    "Saved money compounds. €20/month killed today is €240/year, every year.",
    "What's the fastest way to find subscriptions you forgot about?",
    ["Check your email", "Look for recurring charges in your bank app", "Ask a friend"],
    1,
    "Bank statements show every recurring charge whether you remember signing up or not.",
    "Cancel one subscription you don't use today.",
    "10 min", "Easy", ["saving", "personal-finance"]),
  s("mo-2", "Money", "Idea",
    "The three-fund portfolio in plain English",
    "A boring index strategy that beats most active investors over decades.",
    "A three-fund portfolio holds a domestic stock index, an international stock index, and a bond index. You set the ratio once (e.g. 60/30/10), buy on autopilot, and ignore it. It works because low fees + diversification beats most stock-pickers over 20+ years.",
    "Most people lose to fees and emotional trading. Boring beats clever, on average.",
    "Why does the three-fund portfolio tend to beat active investors over time?",
    ["It picks winning stocks", "Low fees + broad diversification compound", "It uses leverage"],
    1,
    "It's not magic — costs and diversification quietly compound for decades.",
    "Check the expense ratio of any fund you own — under 0.2% is the goal.",
    "10 min", "Easy", ["investing", "index"],
    { name: "Bogleheads", url: "https://www.bogleheads.org/wiki/Three-fund_portfolio" }),
  s("mo-3", "Money", "Tip",
    "Automate one transfer to savings",
    "Make the savings decision once, not every month.",
    "Set up a recurring transfer from your checking account to a separate savings account on payday — even €10 counts. By the time you 'see' your money, the savings are already gone. This is called paying yourself first, and it works because behavior beats willpower.",
    "Behavior beats intelligence in personal finance. Automation is locked-in behavior.",
    "Why does paying yourself first work?",
    ["You earn higher interest", "You save before you can spend it", "It's tax-free"],
    1,
    "Money you never see in checking is money you don't talk yourself out of saving.",
    "Set up a small auto-transfer to savings on your next payday.",
    "10 min", "Easy", ["saving", "habits"]),
  s("mo-4", "Money", "Idea",
    "Why you should max your employer match first",
    "An employer 401(k)/pension match is a 100% return before any market move.",
    "If your employer matches, say, 5% of your salary into a retirement account, every euro you contribute up to that 5% is doubled the moment it lands. There is no investment in the world with a guaranteed instant 100% return — except this one.",
    "Skipping the match is leaving free salary on the table, every paycheck, forever.",
    "What's the typical return on employer-matched retirement contributions, before any investment gain?",
    ["About 5%", "About 100%", "About 7%"],
    1,
    "A full match doubles your contribution instantly — that's a 100% return before the market does anything.",
    "Check whether your job offers a match and you're capturing all of it.",
    "10 min", "Easy", ["retirement", "pension"]),

  // ===== Creativity =====
  s("cr-1", "Creativity", "Tip",
    "The rule of thirds in 60 seconds",
    "A simple framing rule that instantly improves photos and videos.",
    "Imagine your frame split by 2 horizontal and 2 vertical lines (a 3x3 grid). Place your subject — eyes, horizon, or focal point — along one of those lines or at an intersection instead of dead center. The image feels balanced without feeling static.",
    "It's the cheapest way to make every photo and video you make look more intentional.",
    "Where should your subject usually sit in the frame using the rule of thirds?",
    ["Dead center", "Along a third-line or intersection", "In the corner"],
    1,
    "Off-center on a third-line creates natural visual balance the eye prefers.",
    "Take 5 photos today using the grid lines on your phone camera.",
    "5 min", "Easy", ["photography", "composition"]),
  s("cr-2", "Creativity", "Tool",
    "Use Figma's auto-layout to stop fighting alignment",
    "Auto-layout is what separates Figma beginners from designers who ship.",
    "Auto-layout turns a frame into a flexible container. You set padding, gap, and direction once — children rearrange themselves when you add, remove, or resize them. It mirrors how CSS Flexbox works in real code, so designs translate cleanly to dev.",
    "Stops you from manually nudging pixels and keeps designs in sync as content changes.",
    "What does Figma's auto-layout most resemble in real code?",
    ["CSS Grid only", "CSS Flexbox", "HTML tables"],
    1,
    "Auto-layout is essentially Flexbox with a UI — same mental model.",
    "Convert one of your frames to auto-layout today.",
    "15 min", "Medium", ["figma", "design"],
    { name: "Figma auto-layout", url: "https://help.figma.com/hc/en-us/articles/5731482952599" }),
  s("cr-3", "Creativity", "Idea",
    "Constraints kill perfectionism",
    "Hard limits force shipping. Open canvases freeze you.",
    "Pick one constraint before you start: one focal length, one font, one chord, 60 seconds, no editing. The constraint removes most decisions, which removes most resistance. You finish more, learn faster, and develop taste through volume — not theory.",
    "You learn more shipping 10 small imperfect things than planning one perfect one.",
    "Why do constraints help creative output?",
    ["They guarantee quality", "They reduce decisions and resistance", "They make tools cheaper"],
    1,
    "Fewer choices mean less paralysis — your brain spends energy on the work, not the setup.",
    "Make something today with one self-imposed constraint.",
    "20 min", "Easy", ["constraints", "shipping"]),
  s("cr-4", "Creativity", "Tip",
    "Write morning pages to clear mental static",
    "3 pages of stream-of-consciousness writing, by hand, before the day starts.",
    "Morning pages, popularized by Julia Cameron, are 3 pages of unfiltered handwriting first thing after waking. No editing, no rereading. The point isn't to produce good writing — it's to dump anxious or repetitive thoughts onto paper so the rest of the day starts with a clearer head.",
    "Empties the static so you can hear your actual ideas.",
    "What's the goal of morning pages?",
    ["To draft a polished essay", "To dump thoughts and clear mental noise", "To plan your day perfectly"],
    1,
    "It's a brain dump, not writing practice. The output is a clearer head, not a draft.",
    "Write 3 pages by hand tomorrow morning.",
    "20 min", "Easy", ["writing", "habits"]),

  // ===== News & Current Affairs =====
  s("ne-1", "News & Current Affairs", "Idea",
    "Read one long-form story end to end",
    "Headlines train you to react. Long-form trains you to think.",
    "Pick a single in-depth article from a quality outlet (Reuters, FT, The Guardian, The Atlantic) and read it from start to finish without switching tabs. Long-form forces context, nuance, and the messy 'why' behind a story — the parts headlines and tweets strip out.",
    "If you only consume headlines, you understand what happened but not why — which is where every interesting answer lives.",
    "What do you mainly lose by only reading headlines?",
    ["Speed", "Context and the 'why' behind events", "Entertainment"],
    1,
    "Headlines compress events. The reasons, trade-offs, and second-order effects only show up in long-form.",
    "Read one feature article today without switching tabs.",
    "15 min", "Easy", ["news", "focus"],
    { name: "Reuters", url: "https://www.reuters.com" }),
  s("ne-2", "News & Current Affairs", "Idea",
    "Think in second-order effects",
    "Most people stop at the headline. Operators think in consequences.",
    "When you see a major news event — a rate hike, a new regulation, a war — pause and write down 3 ways it could ripple over the next 6–12 months. Who benefits? Who loses? What gets cheaper or scarcer? This trains you to read news as a system, not a stream.",
    "Predicting second-order effects is what separates analysts from headline-readers.",
    "What is a 'second-order effect' of a news event?",
    ["The first reaction by markets", "A downstream consequence over time", "The original event itself"],
    1,
    "First-order: the event. Second-order: what the event causes next.",
    "Pick today's biggest story and write 3 second-order effects in your notes.",
    "20 min", "Medium", ["analysis", "geopolitics"]),
  s("ne-3", "News & Current Affairs", "Tip",
    "Spot a biased headline in 10 seconds",
    "Loaded verbs and missing actors are the easiest tells.",
    "Look for: emotional verbs ('slammed', 'destroyed'), passive voice that hides who did what ('mistakes were made'), and adjectives doing argument work ('controversial plan'). These are stylistic choices that smuggle a conclusion into something framed as a fact.",
    "Once you see these patterns, you can't unsee them — and your media diet improves overnight.",
    "Which is a common sign of bias in a headline?",
    ["A date is included", "Loaded emotional verbs like 'slammed'", "It uses a person's full name"],
    1,
    "Emotional verbs do persuasion work that neutral verbs ('said', 'announced') don't.",
    "Scan today's homepage of any news site and flag 3 biased headlines.",
    "5 min", "Easy", ["media-literacy"]),

  // ===== Mind & Philosophy =====
  s("ph-1", "Mind & Philosophy", "Idea",
    "The Stoic dichotomy of control",
    "The single most useful idea from Stoicism — in one sentence.",
    "Epictetus said: some things are up to us (our judgments, choices, effort), and some things are not (other people, weather, outcomes, the past). Mental energy spent on the second category is wasted. Peace comes from acting fully on the first and accepting the second.",
    "Almost every modern anxiety hack — radical acceptance, focus on inputs, let go of outcomes — is a remix of this idea.",
    "According to Stoicism, what is in our control?",
    ["Other people's actions", "Outcomes and weather", "Our judgments and choices"],
    2,
    "Stoics divide the world into 'up to us' (inner) and 'not up to us' (outer). Peace lives in the first.",
    "Today, when frustrated, ask: 'Is this in my control?' Act only if yes.",
    "10 min", "Easy", ["stoicism"],
    { name: "Meditations (free)", url: "https://classics.mit.edu/Antoninus/meditations.html" }),
  s("ph-2", "Mind & Philosophy", "Idea",
    "Buddhism's two arrows",
    "Pain is unavoidable. Suffering is added on top.",
    "The Buddha taught that when something painful happens (the first arrow), we usually shoot ourselves with a second arrow: the story, blame, and rumination about the pain. The first arrow we can't avoid; the second one we add. Most suffering is the second arrow.",
    "Recognizing the second arrow is the first step to dropping it.",
    "What is 'the second arrow' in Buddhism?",
    ["The original painful event", "Our reactive story and rumination about the pain", "A physical injury"],
    1,
    "First arrow = the actual event. Second arrow = the suffering we manufacture about it.",
    "Next time you feel upset, ask: 'Which part is the second arrow?'",
    "10 min", "Easy", ["buddhism"]),
  s("ph-3", "Mind & Philosophy", "Idea",
    "Socratic questioning, in 4 prompts",
    "A 2,400-year-old tool that still works on modern problems.",
    "When you have a strong opinion or worry, ask yourself: (1) What do I actually mean by this? (2) What's the evidence? (3) What's a strong opposing view? (4) What follows if I'm right — and if I'm wrong? This drags vague feelings into the open where they can be examined.",
    "Most stress is vague. Socratic questions make it specific, and specific things are solvable.",
    "What does Socratic questioning mainly do for your thinking?",
    ["Speeds it up", "Forces clarity by interrogating assumptions", "Makes you agree with others"],
    1,
    "It's a structured way to make hidden assumptions visible.",
    "Pick one worry and run it through the 4 questions today.",
    "15 min", "Medium", ["socrates", "thinking"]),
  s("ph-4", "Mind & Philosophy", "Idea",
    "Epicurus on quiet pleasure",
    "Epicurus is misread as a hedonist. He was closer to a minimalist.",
    "Epicurus argued the highest pleasure isn't excess — it's the absence of pain and anxiety, achieved through simple food, close friends, and a calm mind. Endless desires create endless dissatisfaction. The trick is wanting less, not getting more.",
    "Modern lifestyle inflation is exactly the trap Epicurus warned about 2,300 years ago.",
    "What did Epicurus actually consider the highest pleasure?",
    ["Luxury and excess", "Absence of pain and a calm mind", "Constant new experiences"],
    1,
    "For Epicurus, peace and simple needs beat luxury for sustained happiness.",
    "List 3 things you've wanted lately. Ask which would actually reduce pain vs. add status.",
    "10 min", "Easy", ["epicurus", "minimalism"]),

  // ===== Health & Lifestyle =====
  s("he-1", "Health & Lifestyle", "Tip",
    "Walk 8,000 steps — the daily floor",
    "A walk is the most underrated health intervention there is.",
    "Studies consistently show big drops in all-cause mortality risk between 4,000 and 8,000 steps a day, with diminishing returns after 10,000. Daily walking improves mood, blood sugar, cardiovascular health, and creative thinking — all in one cheap habit.",
    "It's free, it scales with anyone, and the data is unusually clean.",
    "Where does most of the longevity benefit from daily steps appear?",
    ["Above 15,000 steps", "Between 4,000 and 8,000 steps", "Below 2,000 steps"],
    1,
    "The biggest gains happen in the jump from sedentary to ~8,000 steps. After that, returns flatten.",
    "Take a 30-minute walk today, ideally without your phone in your hand.",
    "30 min", "Easy", ["movement"]),
  s("he-2", "Health & Lifestyle", "Tip",
    "Lock a consistent wake-up time",
    "A fixed wake time is the lever that anchors all other sleep advice.",
    "Your circadian rhythm responds more to wake time + morning light than to bedtime. Pick a wake time you can hold every day — including weekends — and get bright light in your eyes within 30 minutes. Sleep onset improves on its own.",
    "Better sleep starts with mornings, not nights.",
    "What anchors your circadian rhythm most reliably?",
    ["A fixed bedtime", "A fixed wake time + morning light", "Avoiding caffeine after lunch"],
    1,
    "Wake time + light is the strongest signal your body uses to set sleep timing.",
    "Set the same alarm for the next 7 days, weekends included.",
    "5 min", "Medium", ["sleep", "habits"]),
  s("he-3", "Health & Lifestyle", "Tip",
    "Most fatigue is mild dehydration",
    "Drink water before you reach for caffeine.",
    "Even mild dehydration (1–2% of body weight) measurably reduces alertness, mood, and short-term memory. Most people wake up dehydrated and immediately top up with coffee, which compounds it. Drinking a full glass on waking and another before lunch fixes most of the slump.",
    "Cheap, fast, real ROI on energy and focus.",
    "What's a common cause of mid-morning fatigue?",
    ["Too much sunlight", "Mild dehydration", "Eating breakfast"],
    1,
    "Mild dehydration measurably tanks alertness — long before you feel 'thirsty'.",
    "Drink one full glass of water on waking tomorrow.",
    "5 min", "Easy", ["hydration"]),
  s("he-4", "Health & Lifestyle", "Idea",
    "Strength training is longevity training",
    "Muscle is the organ of longevity, not vanity.",
    "Adults lose 3–8% of muscle mass per decade after 30 unless they actively train against it. Maintaining muscle protects metabolism, bone density, balance, and independence in old age. 2 short strength sessions per week is enough to slow or reverse the decline for most people.",
    "It's not about looking jacked. It's about being able to carry your own groceries at 80.",
    "How much muscle do adults typically lose per decade after 30 without training?",
    ["Less than 1%", "3–8%", "Over 20%"],
    1,
    "Significant muscle loss starts in your 30s — but training reliably slows or reverses it.",
    "Do one short strength session this week (even bodyweight counts).",
    "30 min", "Medium", ["strength", "longevity"]),

  // ===== Cooking & Skills =====
  s("ck-1", "Cooking & Skills", "Tip",
    "Salt your pasta water like the sea",
    "Under-salted water is why your pasta tastes flat.",
    "Pasta absorbs salt only while it cooks in water. The water should taste clearly salty — about 10g of salt per liter of water. Most home cooks use a fraction of that. The pasta itself stays bland forever afterward, no matter what sauce you add on top.",
    "It's the single fix that makes home pasta taste closer to a good restaurant.",
    "Roughly how much salt per liter of pasta water?",
    ["1g", "10g", "50g"],
    1,
    "About 10g (a heaping teaspoon) per liter — the water should taste like sea water.",
    "Salt your next pot of pasta water properly and taste the difference.",
    "5 min", "Easy", ["pasta", "technique"]),
  s("ck-2", "Cooking & Skills", "Idea",
    "Build a 5-ingredient go-to dinner",
    "A repeatable, healthy weeknight meal you can make on autopilot.",
    "Pick a protein, a carb, a vegetable, a fat, and an acid (e.g. chicken, rice, broccoli, olive oil, lemon). Memorize the ratios and timing once. After 3 cooks, it becomes muscle memory — and replaces 'what should we eat?' with a 25-minute default that's healthier than takeout.",
    "Reliable defaults beat takeout every time.",
    "Why does a 5-ingredient default meal beat takeout long-term?",
    ["It's always cheaper today", "It removes decision friction and is healthier", "It tastes better"],
    1,
    "Defaults work because they remove the decision — that's where takeout usually wins.",
    "Decide your 5 ingredients today, buy them, cook it tonight.",
    "30 min", "Easy", ["weeknight"]),
  s("ck-3", "Cooking & Skills", "Tip",
    "The french omelette is the chef's basic exam",
    "Master one technique-heavy dish and your everyday cooking levels up.",
    "A proper French omelette uses constant motion in a hot non-stick pan, pulling cooked egg toward the center while letting raw egg hit the pan. The result is a soft, almost custardy interior with no browning. The technique teaches you heat control, timing, and confidence with eggs.",
    "Skills transfer. Nailing one technique-heavy dish raises the floor on everything else you cook.",
    "What's the visual goal of a classic French omelette?",
    ["Crispy and golden brown", "Pale, smooth, soft inside", "Dry and firm"],
    1,
    "The signature is no browning and a soft, almost custardy interior.",
    "Watch a 5-minute French omelette video and try one tomorrow.",
    "15 min", "Medium", ["technique", "eggs"],
    { name: "Jacques Pépin omelette", url: "https://www.youtube.com/watch?v=s10etP1p2bU" }),
  s("ck-4", "Cooking & Skills", "Tip",
    "Reset a stuck zipper with a graphite pencil",
    "A small home skill that saves a jacket from the trash.",
    "Rub the teeth of a stuck zipper with a graphite pencil tip on both sides. Graphite is a dry lubricant — it slips between the teeth without attracting dirt the way oil does. Work the slider back and forth gently while the graphite settles in.",
    "Tiny home skills compound into a feeling of competence around your own life.",
    "Why does a graphite pencil work on a stuck zipper?",
    ["Graphite melts the metal", "Graphite is a dry lubricant", "Graphite is magnetic"],
    1,
    "Graphite slips between the teeth without attracting dirt — unlike oil.",
    "Try it on any zipper that's been sticking.",
    "5 min", "Easy", ["home-skills"]),

  // ===== Business =====
  s("bu-1", "Business", "Idea",
    "Jobs to be done: customers 'hire' products",
    "Reframes everything you build around the moment of purchase.",
    "Clayton Christensen's framing: customers don't really buy products — they 'hire' them to make progress in a specific situation. A milkshake might be 'hired' for a long, boring commute. Once you know the job, you stop competing with similar products and start competing with anything that does the same job.",
    "It changes who your real competition is, and what features actually matter.",
    "In Jobs-to-be-Done thinking, what does a customer mainly 'hire' a product for?",
    ["Brand affiliation", "Progress in a specific situation", "Status"],
    1,
    "The 'job' is the progress the customer is trying to make in their life — not a feature list.",
    "For your product (or one you use), write the real 'job' it gets hired for.",
    "20 min", "Medium", ["jtbd", "strategy"],
    { name: "JTBD primer", url: "https://jtbd.info/" }),
  s("bu-2", "Business", "Article",
    "Do things that don't scale",
    "The classic Paul Graham essay on getting your first 100 users.",
    "Early on, founders should do manual, unscalable things: DM users one by one, onboard them personally, hand-deliver the product. It feels wrong because it doesn't scale — but it gives you raw signal about the product, the customer, and the messaging that you can't get any other way.",
    "Cures the 'if we build it they will come' delusion that kills most startups.",
    "Why does Paul Graham recommend doing things that don't scale early on?",
    ["To save money", "To get raw signal and recruit first users manually", "To avoid hiring"],
    1,
    "Manual work early is how you discover the product and the customer at the same time.",
    "DM 5 ideal users today.",
    "10 min", "Easy", ["startups", "yc"],
    { name: "Do Things That Don't Scale", url: "https://www.paulgraham.com/ds.html" }),
  s("bu-3", "Business", "Tip",
    "The 5-second test for landing pages",
    "Show your homepage to a stranger for 5 seconds. Hide it. Ask what we do.",
    "If they can't tell you what your product does, who it's for, and the main benefit after 5 seconds, your homepage is failing. The fix is rarely 'more copy' — it's a clearer headline, a sharper subhead, and an obvious primary action.",
    "Most homepages lose visitors not to competition but to confusion in the first 5 seconds.",
    "What is the 5-second test really measuring?",
    ["Page load speed", "Whether the value prop is instantly clear", "Color contrast"],
    1,
    "It's a brutal but cheap test of clarity, not speed or design polish.",
    "Run the 5-second test on your own (or your favorite) site today.",
    "10 min", "Easy", ["landing-page", "marketing"]),
  s("bu-4", "Business", "Idea",
    "Pricing is positioning",
    "What you charge says more than what you say you do.",
    "If you sell a 'premium' product but charge less than alternatives, the market reads you as the cheap option — regardless of your messaging. Pricing is the loudest signal about who you're for. Raising price often raises perceived quality, narrows your customer base, and improves your margins all at once.",
    "Most early founders under-price by 2–5x and assume cheap will win them market share. It usually wins them low-quality customers and burnout.",
    "What does pricing mainly communicate to the market?",
    ["Your costs", "Your positioning and who you're for", "Your team size"],
    1,
    "Price is positioning — it tells customers which shelf to mentally file you on.",
    "Compare your (or a favorite product's) price to its 3 closest alternatives.",
    "15 min", "Medium", ["pricing", "positioning"]),
];

// Attach real YouTube embed URLs to specific signals so the feed has
// rich video cards out of the box. These are the curated, working URLs.
const VIDEO_URLS: Record<string, string> = {
  "ai-3": "https://www.youtube.com/embed/zjkBMFhNj_g", // Karpathy — Intro to LLMs
  "mo-1": "https://www.youtube.com/embed/THNkf02fBNI", // George Kamel — Stop wasting money
  "ph-1": "https://www.youtube.com/embed/EFkyxzJtiv4", // Einzelgänger — Stoicism
  "cr-1": "https://www.youtube.com/embed/o9t9R7Zn7C0", // Struthless — Rule of thirds
  "he-2": "https://www.youtube.com/embed/h2aWYjSA1Jc", // Huberman — Morning routine
  "ck-3": "https://www.youtube.com/embed/YEWhMQpBYS0", // Joshua Weissman — Quick skill
};

for (const sig of DEFAULT_SIGNALS) {
  const v = VIDEO_URLS[sig.id];
  if (v) {
    sig.videoUrl = v;
    sig.contentType = "Video";
  }
}
